export const Category = [
    {
        id:1,
        title:"Go",
        label:"",
        image:"https://www.smoothmovepeople.net/wp-content/uploads/02g71677.jpg",
        link:"",
    }, 
    {
        id:2,
        title:"Send",
        label:"",
        image:"https://arkpol.com/wp/wp-content/uploads/2020/03/AdobeStock_218788300.jpeg",
        link:"",
    },
    {
        id:3,
        title:"Food",
        label:"",
        image:"https://i.pinimg.com/originals/8b/26/4b/8b264b78afef7ee93227346912c91fa8.jpg",
        link:"",
    },
    {
        id:4,
        title:"GROCERY",
        label:"upcoming",
        image:"https://g.foolcdn.com/image/?url=https%3A//g.foolcdn.com/editorial/images/604301/naturalgrocery.jpg&w=2000&op=resize",
        link:"",
    },
    {
        id:5,
        title:"MEDICAL",
        label:"upcoming",
        image:"https://medicalwinglocums.co.uk/wp-content/uploads/2020/03/clients.jpg",
        link:"",
    }
]