export const FeatureSlider = [
  {
      id:1,
      title:"Burger",
      image:'./images/temp/best-medicine.jpg',
  },
  {
      id:2,
      title:"Pizza",
      image:'./images/temp/pizza.jpg',
  },
  {
      id:3,
      title:"Cakes",
      image:'./images/temp/grossary.jpg',
  },
  {
      id:4,
      title:"Tacos",
      image:'./images/temp/go-send.jpg',
  }
]